insert into user(name, age) values('Harrison', 26)
insert into user(name, age) values('Boyns', 26)
insert into user(name, age) values('Max', 26)
insert into user(name, age) values('Jude', 26)
insert into posts values(1, 'Hello World', 1)
insert into posts values(2, 'World', 1)
insert into posts values(3, 'Hello', 1)
insert into posts values(4, 'Hello', 2)
insert into posts values(5, 'Hello', 2)
